version: 2

#orbs:
#  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo
    
    steps:
      - checkout
#      - python/load-cache
#      - python/install-deps
#      - python/save-cache

      - run:
          name: install dependencies
#          command: ./manage.py test
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics

